# Generated by Django 2.0.2 on 2018-02-12 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_user_curtain_statu'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='temp',
            field=models.IntegerField(default=0),
        ),
    ]
